### ISSUE TITLE
S4PE Grid edit on CASP

### ISSUE THREAD

**Issue by ProgMizer** [Kuree/Sims4Tools#21] opened 2014-11-14 16:36 UTC
I just found if I use the grid edit on CASP sections it gets corrupted... exporting the before and after file looks like the data after the Unk4B (0x00000800) and the TGIList gets deleted.

**Comment by Kuree** [comment] 2015-02-18 14:07
Sorry I couldn't reproduce your issue. I'll close the issue now. If you find the bug still exists, you can still comment it and I'll reopen the issue.

**Closed by Kuree** 2015-02-18 14:07 UTC
